name: parachutes
version: '${project.version}'
main: org.oreo.parachutes.Parachutes
api-version: '1.20'

commands:

  parachute:
    description: Gives the parachute the player
    usage: /<command>
    aliases: [parachute]